### ISSUE TITLE
Allow Halyard to update the contents of the halconfig bucket

### ISSUE THREAD

**Issue by lwander** [spinnaker/halyard#114]
The halconfig bucket contains all of the Spinnaker profile stubs for each microservce, as well as the Bill of Materials (BOM) for each release. Some part of the Spinnaker release process needs to assume the responsibility of updating this bucket, and it makes the most sense to have Halyard own this since it'll be the bucket's sole consumer. 

My thinking is that Halyard will only expose these operations:

1. Upload a new BOM.
2. Given a BOM and an artifact's (e.g. clouddriver) config, place the config in the right spot as referenced in the BOM.

This leaves the remainder of the release tooling to generate the BOM, checkout each artifact's repo at the correct commit as specified by the BOM, and provide Halyard with the required files.

WDYT, @ewiseblatt & @jtk54?

**Comment by ewiseblatt** [comment]
Do we really need another service? Couldnt the bucket have write
permissions that restrict to us and we have policy that says be careful?
That would be simpler and easier form an OSS standpoint rather than needing
people to stand up their own services for their own builds.

Or is this a command that you run a halyard CLI to do? This too is ok, but
doesnt make sense for operators using the CLI since they dont write to
halyard. So I'm not seeing the value there.

I'm not sure what concern you are trying to protect here. If the publisher
is constructing the BOM and giving it to halyard, it could just write it
into the bucket. The individual artifacts can be more complicated, but
sounds like that is ultimately straightforward to. Couldnt you just put the
halyard write logic into the build tools? If there werent a language
conflict, I'd suggest sharing library code to keep the policy encapsulated.
But if it is low volatility then for the time being it doesnt matter.

**Comment by lwander** [comment]
This is using haylard - not another service. If the operator will use
halyard to configure Spinnaker, I don't see much of a burden to use halyard
to do custom builds. After all, if they don't want to use halyard with
their Spinnaker installation they don't need to update their halconfig
bucket, which is fine.

The concern is that the bucket's layout/structure shouldn't leak beyond the
sole consumer of that bucket.

**Comment by lwander** [comment]
ping @ewiseblatt

**Comment by ewiseblatt** [comment]
ok. so halyard will be able to write to the native buckets in aws, azure, and openstack as well? Or at least a straightforward migration path to get there?

Microsoft (or an azure customer) should be able to do custom builds if they need. They not only need to be able to write to their own storage, but use the infrastructure they are using?

It's ok if the "platform provider" has the responsibility of actually implementing the halyard support for that. But they need to be able to.

Does "placing the config in the right spot" also include customer added configs?

**Comment by lwander** [comment]
> ok. so halyard will be able to write to the native buckets in aws, azure, and openstack as well? Or at least a straightforward migration path to get there?
> Microsoft (or an azure customer) should be able to do custom builds if they need. They not only need to be able to write to their own storage, but use the infrastructure they are using?

Yup that's right.

> It's ok if the "platform provider" has the responsibility of actually implementing the halyard support for that. But they need to be able to.

I agree, that seems reasonable.

> Does "placing the config in the right spot" also include customer added configs?

This is only for the base-config, meaning the stuff that every deployment of a service should have in common - this is more relevant to the custom Spinnaker builds than the customer/consumer of those builds. The idea that the customer can override any config with their own using Halyard still stands either way.

**Comment by ewiseblatt** [comment]
SGTM. Regarding configs, it isnt "override" but introduce their own -local
files. The customer we've been working with this week builds their own debs
only because they add their own configs into them. If halyard injected them
with the install then they wouldnt need to do that and could use off the
shelf debs.

**Comment by lwander** [comment]
https://github.com/spinnaker/halyard/pull/180
