### ISSUE TITLE
Support Azure configuration

### ISSUE THREAD

**Issue by lwander** [spinnaker/halyard#119]
The linked PRs & details in #71 will be helpful.

**Comment by lwander** [comment]
@EricJizbaMSFT ready to close this?

**Comment by EricJizbaMSFT** [comment]
I've got two things left to do:
1. Add Azure to setting.js
2. Add Azure Storage to front50

**Comment by lwander** [comment]
Hey, when you get a chance could you also make sure the Azure OAuth provider works with `hal config security oauth2 edit --provider azure --client-id <> --client-secret <>`? I've implemented all the Azure bits, I just don't have any way to verify.

**Comment by EricJizbaMSFT** [comment]
FYI I haven't forgotten about this - I've just been occupied with other tasks. I should be able to try out the OAuth provider next week and hope to get to the other items soon

Speaking of... @lwander any thoughts on how I should do the azure storage config? Both aws and gce use the 'bucket' terminology, but Azure does not. I could either add the Azure parameters to the current storage command (a little more confusing for users IMO) or we could abstract out the storage command for all providers. I'm leaning the second option, but it's obviously a bigger change so I thought I'd run it by you first

**Comment by lwander** [comment]
No worries. I'd prefer if the tool felt native to users of each cloud provider, rather than tried to fit everything into the same abstraction - so trying to adopt the Azure terminology where appropriate feels best. What's the change in naming you're proposing?

**Comment by EricJizbaMSFT** [comment]
For gcs or s3 it would be the exact same except you have to specify the provider before 'edit':
`hal config storage gcs edit --account-name my-google-account --bucket bucket123 --location westus --root-folder spinnaker`

For azs, I would do something like this:
`hal config storage azs edit --storage-account-name storageAccount123 --storage-account-key secretkey --container-name spinnaker`
> In Azure, an 'account' is analogous to a 'bucket'. So the 'storage-account-name' has nothing to do with a spinnaker account. In fact, azure just uses a key to authenticate and has no use for spinnaker accounts or location like gcs/s3.

Finally, since Azure doesn't use a spinnaker account, we can't automatically detect which provider to enable. I think we would want to add a command like this:
`hal config storage edit --provider <gcs|azs|s3|cassandra>`
> Not sure if this should be 'edit', 'set', 'change' or something else
Alternatively, we could add a "enable/disable" command under each provider, but I don't think that makes sense since only one can be enabled at a time.

**Comment by lwander** [comment]
That seems like a good solution, both breaking the commands out by provider as well as using a `--provider` flag.

Only thing I don't understand is: 

> Finally, since Azure doesn't use a spinnaker account, 

How do you authenticate with Azure?

**Comment by EricJizbaMSFT** [comment]
Azure just authenticates with a key (a key that's only used for storage)

**Comment by lwander** [comment]
Cool, makes sense. Are you willing to take this on? You don't need to verify the providers other than Azure.

**Comment by EricJizbaMSFT** [comment]
Yeah I can take this on
