### ISSUE TITLE
The `postInstall.sh` restarts the service without a user

### ISSUE THREAD

**Issue by TYsewyn** [spinnaker/halyard#563]
At the end of the `postInstall.sh` script the halyard service will be restarted.
This in turn will execute following command:

`sudo -u $(cat /var/spinnaker/config/halyard-user) -g $(cat /var/spinnaker/config/halyard-user) /opt/halyard/bin/halyard 2>&1 > /var/log/spinnaker/halyard/halyard.log &`

Since `/var/spinnaker/config/halyard-user` will only be written after the installation, and therefor after the `postInstall.sh` script, this results in a faulty restart of the service.

**Comment by lwander** [comment]
This one's a bit tricky to fix, since the user needs to specify who to run Halyard as before the install can be considered successful. The only default that comes to mind is "root", and that feels off. The service restart was added to the postInstall script to ensure package updates were successful, after the Halyard had been installed correctly once.
