### ISSUE TITLE
Unclear how/if possible to configure Deck service to use a "LoadBalancer" type with the Kubernetes cloud provider

### ISSUE THREAD

**Issue by keyan** [spinnaker/halyard#579]
After issuing a `deploy` with halyard I see a warning that I haven't properly configured a UI domain, but there isn't any information in the docs or via Halyard's help output on how to do this. The results Kubernetes `service` is a `ClusterIp` type rather than a `LoadBalancer` type, so I am unable to reach the UI. I worked around this by manually changing the service configuration YAML, but I am assuming there is (or should be) a proper way to configure this via Halyard.

Output from `hal deploy apply`:
```
$ hal deploy apply
+ Get current deployment
  Success
+ Apply deployment
  Success
+ Deploy spin-clouddriver
  Success
+ Deploy spin-front50
  Success
+ Deploy spin-orca
  Success
+ Deploy spin-deck
  Success
+ Deploy spin-echo
  Success
+ Deploy spin-gate
  Success
+ Deploy spin-igor
  Success


+ Deploy spin-rosco
  Success

Problems in default.security:
- WARNING Your UI or API domain does not have override base URLs
  set even though your Spinnaker deployment is a Distributed deployment on a
  remote cloud provider. As a result, you will need to open SSH tunnels against
  that deployment to access Spinnaker.
? We recommend that you instead configure an authentication
  mechanism (OAuth2, SAML2, or x509) to make it easier to access Spinnaker
  securely, and then register the intended Domain and IP addresses that your
  publicly facing services will be using.

+ Run `hal deploy connect` to connect to Spinnaker.
```

**Comment by lwander** [comment]
Please reopen if the linked answer doesn't help: https://www.spinnaker.io/setup/quickstart/faq/#i-want-to-expose-the-distributed-kubernetes-hosted-spinnaker-publicly

**Comment by pweaver** [comment]
I am trying to follow the guide to setup an external spinmaker service. When I edit the k8s file using
kubectl edit svc spin-deck -n spinnaker
I get `unexpected EOF; some request body already written.`

This is only happening when I try to change the type to LoadBalancer. (Just changing the port works correctly). I am am stuck on why kubernetes is not taking the change. 

I am using spinnaker v1.5.0 and kubernetes 1.8.3-gke.0. Otherwise I am following the guide as written.
