### ISSUE TITLE
Docker Registry Addition should allow empty GCR

### ISSUE THREAD

**Issue by nparks-kenzan** [spinnaker/halyard#608]
When  attempting `hal config provider docker-registry account add ` for GCR followed up by `hal config provider docker-registry enable`

You get a message like:

`
Problems in default.provider.dockerRegistry.imagerepository:
! ERROR Your docker registry has no repositories specified, and the
  registry's catalog is empty.
? Manually specify some repositories for this docker registry to
  index.
`

If your GCP project does not have any images in it. Which, if you are starting up a project from nothing that would be the case. 

However, putting something in the registry via the Google Cloud Shell with:

- docker pull nginx
- docker tag nginx:latest gcr.io/PROJECT_NAME/nginx
- gcloud docker -- push gcr.io/PROJECT_NAME/nginx

seems to make everything better. 

SO, the BUG is: **Halyard docker registry account add / enable for GCR should not blow up on empty registry**

**Comment by lwander** [comment]
This is intentional - before Halyard we frequently dealt with users who couldn't figure why they couldn't deploy anything even though they had specified a docker registry. Having this check prevents that confusion. 

However, I agree that the new user experience can be improved. If you have a suggestion for an improved remediation/error message please open a PR against these lines: https://github.com/spinnaker/halyard/blob/master/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidator.java#L94-L95

**Comment by nparks-kenzan** [comment]
Okay, I can see that. Maybe a warning of "You are going to be sorry later"

**Comment by lwander** [comment]
I can get behind that, are you willing to open a PR? You'll need to change the message, maybe add something to the remediation, and most importantly change the severity from ERROR to WARNING in that above code snippet I highlighted
