### ISSUE TITLE
More fine-grained permissions for GCP service accounts

### ISSUE THREAD

**Issue by wheleph** [spinnaker/halyard#681]
According to https://www.spinnaker.io/setup/quickstart/halyard-gke/ it's necessary for `halyard-service-account` to have role `roles/container.admin` which is a pretty powerful one. But since halyard only manages Spinnaker, it probably only needs access to the 'spinnaker' namespace in the cluster. 

Is there any documentation that describes exactly what types of operations halyard does on a k8s cluster?

**Comment by lwander** [comment]
You're right, Halyard only needs to touch resources in the `spinnaker` namespace. However, you'll likely want to pass stronger permissions on to Spinnaker (since it will probably be creating resources in other namespaces). If you want to provide Halyard with the strictest permissions possible, create another kubernetes provider account within Halyard used only for bootstrapping, and provide it with a separate kubernetes context whose user has access only to the `spinnaker` namespace.

@skim1420 wrote this quickstart and can help find more restrictive permissions (I think the VM only needs to be able to download k8s credentials).

**Comment by wheleph** [comment]
Thank
